# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mysqldb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score_Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuNum', models.IntegerField()),
                ('NAME', models.TextField()),
                ('COLOR', models.IntegerField()),
                ('SKETCH', models.IntegerField()),
                ('LINEDRAW', models.IntegerField()),
                ('TOTAL', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
