# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mysqldb', '0002_auto_20170816_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score_graph',
            name='StuNum',
        ),
    ]
